table fact_board_flow
	lineageTag: 10000001-0001-0001-0007-000000000001
	sourceLineageTag: fact_board_flow

	measure 'WIP Count' = SUM(fact_board_flow[item_count])
		formatString: #,##0
		lineageTag: 20000001-0001-0001-0007-000000000001

	column project_name
		dataType: string
		lineageTag: 30000001-0001-0001-0007-000000000001
		sourceLineageTag: project_name
		summarizeBy: none
		sourceColumn: project_name

	column board_column
		dataType: string
		lineageTag: 30000001-0001-0001-0007-000000000002
		sourceLineageTag: board_column
		summarizeBy: none
		sourceColumn: board_column

	column item_count
		dataType: int64
		formatString: #,##0
		lineageTag: 30000001-0001-0001-0007-000000000003
		sourceLineageTag: item_count
		summarizeBy: sum
		sourceColumn: item_count

	column total_story_points
		dataType: double
		formatString: #,##0.0
		lineageTag: 30000001-0001-0001-0007-000000000004
		sourceLineageTag: total_story_points
		summarizeBy: sum
		sourceColumn: total_story_points

	column assignee_count
		dataType: int64
		formatString: #,##0
		lineageTag: 30000001-0001-0001-0007-000000000005
		sourceLineageTag: assignee_count
		summarizeBy: sum
		sourceColumn: assignee_count

	column avg_age_days
		dataType: double
		formatString: #,##0.0
		lineageTag: 30000001-0001-0001-0007-000000000006
		sourceLineageTag: avg_age_days
		summarizeBy: average
		sourceColumn: avg_age_days

	column refreshed_at
		dataType: dateTime
		isHidden
		lineageTag: 30000001-0001-0001-0007-000000000007
		sourceLineageTag: refreshed_at
		summarizeBy: none
		sourceColumn: refreshed_at

	partition fact_board_flow = entity
		mode: directLake
		source
			entityName: fact_board_flow
			expressionSource: 'DirectLake - ado_gold'
